openapi: 3.0.1
info:
  title: Payment
  description: Oriogin code test
  termsOfService: http://swagger.io/terms/
  contact:
    email: prakanth@gmail.com
  version: 1.0.0
servers:
  - url: /api
tags:
  - name: payment
paths:
  /payment:
    post:
      tags:
        - payment
      summary: Make a payment
      operationId: payment
      requestBody:
        description: Pet object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
      x-codegen-request-body-name: body
components:
  schemas:
    Payment:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        referenceNumber:
          type: string
        bsb:
          type: integer
          format: int32
        accountNumber:
          type: integer
          format: int32
        amount:
          type: integer
          format: int32
